

#' Primary lung cancer results
#'
#' Primary lung cancer results in the form of Hidden Markov Models saved as RData, generated by the \pkg{AneuFinder} package. 
#'
#' @docType data
#' @name primary_lung
#' @aliases primary lung
#' @format Files with \code{aneuHMM} objects.
#' @source Patient material from a primary small cell lung cancer of a 79 year old women. For details see TODO:insert publication.
NULL


#' Liver metastasis results
#'
#' Liver metastasis results in the form of Hidden Markov Models saved as RData, generated by the \pkg{AneuFinder} package. 
#'
#' @docType data
#' @name metastasis_liver
#' @aliases metastasis liver
#' @format Files with \code{aneuHMM} objects.
#' @source Patient material from a liver metastasis of a 79 year old women. For details see TODO:insert publication.
NULL


#' Example BAM-file
#'
#' A BAM-file for demonstration purposes of the functions in package \pkg{AneuFinder}.
#'
#' @docType data
#' @name BB150803_IV_074
#' @aliases bam
#' @format A BAM file with aligned reads.
#' @source A single cell from T-cell Acute Lymphoblastic Leukemia in mouse. The file has been downsampled to 20\% of the coverage to reduce the file size. For further details see TODO: insert publication (tumor ID T386).
NULL


#' Example BED-file
#'
#' A BED-file for demonstration purposes of the functions in package \pkg{AneuFinder}.
#'
#' @docType data
#' @name KK150311_VI_07
#' @aliases bed
#' @format A BED file with aligned reads.
#' @source A single cell with Strand-seq reads. Unpublished data.
NULL


#' Diploid BAM-file
#'
#' A BAM-file with reads from a diploid human brain cell for demonstration purposes of the functions in package \pkg{AneuFinder}.
#'
#' @docType data
#' @name hg19_diploid
#' @aliases diploid
#' @format A BED file with aligned reads.
#' @source A single cell with WGSCS reads of a human brain cell. Unpublished data.
NULL

